@extends('layouts.tu')
@section('content')
<div class="space-y-6">
<div><h1 class="text-2xl md:text-3xl font-extrabold text-teal-primary-dark flex items-center gap-2"><x-heroicon-o-trophy class="w-7 h-7"/> Prestasi Siswa</h1><p class="mt-1 text-sm text-gray-500">Kelola data prestasi siswa.</p></div>
<div class="bg-white rounded-card shadow-card p-5 md:p-6 border-l-[6px] border-l-teal-primary">
    <form method="POST" action="{{route('tu.prestasi.store')}}" class="grid grid-cols-1 md:grid-cols-4 gap-3 items-end">@csrf
    <select name="siswa_id" class="block w-full border-teal-primary/20 rounded-card" required><option value="">Pilih Siswa</option>@foreach($siswas as $s)<option value="{{$s->id}}">{{$s->nama_siswa}}</option>@endforeach</select>
    <div><x-text-input name="nama_prestasi" placeholder="Nama Prestasi" class="block w-full" required/></div>
    <div><x-text-input name="tingkat" placeholder="Tingkat" class="block w-full"/></div>
    <div><x-text-input name="penyelenggara" placeholder="Penyelenggara" class="block w-full"/></div>
    <div><x-text-input name="tahun" type="number" placeholder="Tahun" class="block w-full"/></div>
    <div><x-text-input name="keterangan" placeholder="Keterangan" class="block w-full"/></div>
    <button class="btn-primary md:col-span-2">Tambah</button></form>
</div>
<div class="bg-white rounded-card shadow-card overflow-hidden"><table class="w-full text-sm"><thead class="bg-surface-base text-left"><tr><th class="px-4 py-3 font-extrabold text-xs uppercase">Siswa</th><th class="px-4 py-3 font-extrabold text-xs uppercase">Prestasi</th><th class="px-4 py-3 font-extrabold text-xs uppercase hidden sm:table-cell">Tingkat</th><th class="px-4 py-3 font-extrabold text-xs uppercase">Tahun</th><th class="px-4 py-3 text-right font-extrabold text-xs uppercase">Aksi</th></tr></thead>
<tbody>@forelse($prestasis as $p)<tr><td class="px-4 py-3 font-bold">{{$p->siswa->nama_siswa??'-'}}</td><td class="px-4 py-3">{{$p->nama_prestasi}}</td><td class="px-4 py-3 hidden sm:table-cell"><span class="px-2 py-0.5 rounded-pill text-xs font-bold bg-gold/10 text-gold-dark">{{$p->tingkat??'-'}}</span></td><td class="px-4 py-3">{{$p->tahun??'-'}}</td><td class="px-4 py-3 text-right"><button onclick="document.getElementById('pr-{{$p->id}}').classList.toggle('hidden')" class="p-1 text-sky hover:bg-sky/5 rounded"><x-heroicon-o-pencil-square class="w-4 h-4"/></button><form method="POST" action="{{route('tu.prestasi.destroy',$p)}}" class="inline" onsubmit="return confirm('Hapus?')">@csrf @method('DELETE')<button class="p-1 text-coral hover:bg-coral/5 rounded"><x-heroicon-o-trash class="w-4 h-4"/></button></form></td></tr>
<tr id="pr-{{$p->id}}" class="hidden bg-surface-base/50"><td colspan="5" class="px-4 py-2"><form method="POST" action="{{route('tu.prestasi.update',$p)}}" class="grid grid-cols-1 md:grid-cols-4 gap-3">@csrf @method('PUT')<x-text-input name="nama_prestasi" :value="$p->nama_prestasi" class="block w-full" required/><x-text-input name="tingkat" :value="$p->tingkat" class="block w-full"/><x-text-input name="penyelenggara" :value="$p->penyelenggara" class="block w-full"/><x-text-input name="tahun" type="number" :value="$p->tahun" class="block w-full"/><x-text-input name="keterangan" :value="$p->keterangan" class="block w-full"/><button class="btn-primary">Simpan</button></form></td></tr>@empty<tr><td colspan="5" class="px-4 py-12 text-center text-gray-400">Belum ada data.</td></tr>@endforelse</tbody></table><div class="px-4 py-3 border-t">{{$prestasis->links()}}</div></div></div></div>
@endsection