/www/wwwroot/km.smkabdinegara.sch.id/storage/logs/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 640 www www
    sharedscripts
    postrotate
        systemctl reload raporkm-queue-worker > /dev/null 2>&1 || true
    endscript
}
